---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: keda
spec:
  project: default
  source:
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 'v2.14.2'
    chart: keda
    helm:
      values: |
        watchNamespace: ""
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keda
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaled-object
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: argocd-apps-bluebird-chart
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"