apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: keda
spec:
  project: default
  source:
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 'v2.14.2'
    chart: keda
    helm:
      values: |
        watchNamespace: ""
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keda
  syncPolicy:
    automated:
      selfHeal: true
      prune: true