replicaCount: 1

# Pass in your ECR Repo URI
image:
  repository: "211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird"
  pullPolicy: Always
  tag: "v1.0"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Pass in your LB Endpoint
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "a2fe7fe2033a743bab013336094898b8-d27b9e25b989b058.elb.us-east-1.amazonaws.com"
      paths:
        - path: /
          pathType: ImplementationSpecific

clusterSecretStore:
  name: "aws-secrets"
  region: "us-east-1"
  serviceAccountName: "aws-secrets-access"
  namespace: "bluebird"

externalSecret:
  name: "external-secrets"
  namespace: "bluebird"
  refreshInterval: "1h"
  secretStoreName: "aws-secrets"
  targetName: "rds-credentials-k8s"
  # targetNamespace: "bluebird"
  creationPolicy: "Owner"
  secretsKey: "arn:aws:secretsmanager:us-east-1:211125651847:secret:secrets-QiNWs4"

secret:
  name: rds-credentials-k8s