replicaCount: 1

# Pass in your ECR Repo URI
image:
  repository: "211125651847.dkr.ecr.us-east-1.amazonaws.com/bluebird"
  pullPolicy: Always
  tag: "v1.0"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Pass in your LB Endpoint
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "ac1693f6038af4ac4973fcfbcd90b7b5-2953ccb6edb70edd.elb.us-east-1.amazonaws.com"
      paths:
        - path: /
          pathType: ImplementationSpecific

clusterSecretStore:
  name: "aws-secrets"
  region: "us-east-1"
  serviceAccountName: "aws-secrets-access"
  namespace: "bluebird"

externalSecret:
  name: "external-secrets"
  namespace: "external-secrets"
  refreshInterval: "1h"
  secretStoreName: "aws-secrets"
  targetName: "rds-credentials-k8s"
  targetNamespace: "bluebird"
  creationPolicy: "Owner"
  secretsKey: "arn:aws:secretsmanager:us-east-1:211125651847:secret:secrets-a3GkW3"

# serviceAccount:
#   create: true
#   name: "external-secrets-operator"
#   namespace: "bluebird"

secret:
  name: rds-credentials-k8s